import React, {useState} from 'react';
import Head from 'next/head'
import Link from 'next/link';
import Header from '../components/ui/Header';

// * UI
import {makeStyles} from '@material-ui/core';

const useStyles = makeStyles((theme) => ({

    })
);
export default function Home() {

    const classes = useStyles();

    return (
        <React.Fragment>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href={"/favicon.ico"}/>
            </Head>
            <Header />

        </React.Fragment>
    )
}
